export const FECTH_CATEGORY = 'home/FECTH_CATEGORY';
export const FECTH_CATEGORY_SUCCEEDED = 'home/FECTH_CATEGORY_SUCCEEDED';
export const FECTH_CATEGORY_FAILED = 'home/FECTH_CATEGORY_FAILED';

export const FETCH_IMAGES = 'home/FETCH_IMAGES';
export const FETCH_IMAGES_SUCCEEDED = 'home/FETCH_IMAGES_SUCCEEDED';
export const FETCH_IMAGES_FAILDED = 'home/FETCH_IMAGES_FAILDED';
