export const FECTH_CATEGORY = 'home/FECTH_CATEGORY';
export const FECTH_CATEGORY_SUCCEEDED = 'home/FECTH_CATEGORY_SUCCEEDED';
export const FECTH_CATEGORY_FAILED = 'home/FECTH_CATEGORY_FAILED';

export const FETCH_IMAGES = 'home/FETCH_IMAGES';
export const FETCH_IMAGES_SUCCEEDED = 'home/FETCH_IMAGES_SUCCEEDED';
export const FETCH_IMAGES_FAILDED = 'home/FETCH_IMAGES_FAILDED';

export const FETCH_PRODUCT = 'home/FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCEEDED = 'home/FETCH_PRODUCT_SUCCEEDED';
export const FETCH_PRODUCT_FAILDED = 'home/FETCH_PRODUCT_FAILDED';
